from datetime import datetime, timedelta
from api_key_models import PerformerProfile, Gender, SexualPreference, Ethnicity
import random

# Sample performer profiles data
SAMPLE_PERFORMERS = [
    # Male Performers
    {
        "user_id": "male_performer_001",
        "stage_name": "Alex Thunder",
        "bio": "Fitness enthusiast and adventure seeker. Love connecting with people and sharing exciting moments. Always up for a good conversation and memorable experiences.",
        "age": 28,
        "gender": Gender.MALE,
        "sexual_preference": SexualPreference.STRAIGHT,
        "ethnicity": Ethnicity.WHITE,
        "country": "United States",
        "state": "California",
        "city": "Los Angeles",
        "show_exact_location": True,
        "height_cm": 185,
        "weight_kg": 80,
        "body_type": "Athletic",
        "hair_color": "Brown",
        "eye_color": "Blue",
        "experience_level": "experienced",
        "specialties": ["fitness", "adventure", "conversation"],
        "languages": ["english", "spanish"],
        "online_status": "online",
        "timezone": "America/Los_Angeles",
        "rates": {"private_show": 50.0, "group_show": 25.0},
        "is_verified": True,
        "total_views": 15420,
        "total_likes": 892,
        "total_shows": 156,
        "average_rating": 4.8,
        "rating_count": 124
    },
    {
        "user_id": "male_performer_002",
        "stage_name": "Marcus King",
        "bio": "Professional dancer and artist. Passionate about music, creativity, and bringing joy to others. Let's create some magic together!",
        "age": 25,
        "gender": Gender.MALE,
        "sexual_preference": SexualPreference.BISEXUAL,
        "ethnicity": Ethnicity.BLACK,
        "country": "United States",
        "state": "New York",
        "city": "New York City",
        "show_exact_location": True,
        "height_cm": 180,
        "weight_kg": 75,
        "body_type": "Lean",
        "hair_color": "Black",
        "eye_color": "Brown",
        "experience_level": "experienced",
        "specialties": ["dancing", "music", "artistic"],
        "languages": ["english"],
        "online_status": "online",
        "timezone": "America/New_York",
        "rates": {"private_show": 45.0, "group_show": 20.0},
        "is_verified": True,
        "total_views": 12890,
        "total_likes": 756,
        "total_shows": 143,
        "average_rating": 4.7,
        "rating_count": 98
    },
    {
        "user_id": "male_performer_003",
        "stage_name": "Diego Fuego",
        "bio": "Latin charm meets modern charisma. Chef by day, entertainer by night. Let me spice up your evening with passion and flavor!",
        "age": 32,
        "gender": Gender.MALE,
        "sexual_preference": SexualPreference.STRAIGHT,
        "ethnicity": Ethnicity.HISPANIC,
        "country": "United States",
        "state": "Florida",
        "city": "Miami",
        "show_exact_location": True,
        "height_cm": 178,
        "weight_kg": 82,
        "body_type": "Muscular",
        "hair_color": "Black",
        "eye_color": "Brown",
        "experience_level": "expert",
        "specialties": ["cooking", "latin_culture", "romance"],
        "languages": ["english", "spanish"],
        "online_status": "offline",
        "timezone": "America/New_York",
        "rates": {"private_show": 60.0, "group_show": 30.0},
        "is_verified": True,
        "total_views": 18760,
        "total_likes": 1120,
        "total_shows": 203,
        "average_rating": 4.9,
        "rating_count": 156
    },
    {
        "user_id": "male_performer_004",
        "stage_name": "Ryan Steel",
        "bio": "Former military, now bringing discipline and excitement to your screen. Outdoor enthusiast who loves hiking, camping, and new adventures.",
        "age": 29,
        "gender": Gender.MALE,
        "sexual_preference": SexualPreference.GAY,
        "ethnicity": Ethnicity.WHITE,
        "country": "United States",
        "state": "Colorado",
        "city": "Denver",
        "show_exact_location": False,
        "height_cm": 183,
        "weight_kg": 85,
        "body_type": "Athletic",
        "hair_color": "Blonde",
        "eye_color": "Green",
        "experience_level": "experienced",
        "specialties": ["outdoor", "fitness", "military"],
        "languages": ["english"],
        "online_status": "online",
        "timezone": "America/Denver",
        "rates": {"private_show": 55.0, "group_show": 28.0},
        "is_verified": True,
        "total_views": 13450,
        "total_likes": 823,
        "total_shows": 167,
        "average_rating": 4.6,
        "rating_count": 134
    },
    {
        "user_id": "male_performer_005",
        "stage_name": "Kai Ocean",
        "bio": "Surfer and beach lover from Hawaii. Bringing island vibes and positive energy. Life's a wave, let's ride it together!",
        "age": 26,
        "gender": Gender.MALE,
        "sexual_preference": SexualPreference.PANSEXUAL,
        "ethnicity": Ethnicity.PACIFIC_ISLANDER,
        "country": "United States",
        "state": "Hawaii",
        "city": "Honolulu",
        "show_exact_location": True,
        "height_cm": 175,
        "weight_kg": 70,
        "body_type": "Lean",
        "hair_color": "Brown",
        "eye_color": "Brown",
        "experience_level": "intermediate",
        "specialties": ["surfing", "beach", "wellness"],
        "languages": ["english", "hawaiian"],
        "online_status": "online",
        "timezone": "Pacific/Honolulu",
        "rates": {"private_show": 40.0, "group_show": 18.0},
        "is_verified": False,
        "total_views": 9870,
        "total_likes": 567,
        "total_shows": 89,
        "average_rating": 4.5,
        "rating_count": 67
    },
    {
        "user_id": "male_performer_006",
        "stage_name": "James Scholar",
        "bio": "PhD student by day, charming companion by night. Love deep conversations, literature, and intellectual connections. Let's explore minds and hearts.",
        "age": 27,
        "gender": Gender.MALE,
        "sexual_preference": SexualPreference.BISEXUAL,
        "ethnicity": Ethnicity.ASIAN,
        "country": "United States",
        "state": "Massachusetts",
        "city": "Boston",
        "show_exact_location": False,
        "height_cm": 172,
        "weight_kg": 68,
        "body_type": "Slim",
        "hair_color": "Black",
        "eye_color": "Brown",
        "experience_level": "intermediate",
        "specialties": ["intellectual", "literature", "conversation"],
        "languages": ["english", "mandarin"],
        "online_status": "offline",
        "timezone": "America/New_York",
        "rates": {"private_show": 35.0, "group_show": 15.0},
        "is_verified": True,
        "total_views": 8650,
        "total_likes": 445,
        "total_shows": 72,
        "average_rating": 4.4,
        "rating_count": 56
    },

    # Female Performers
    {
        "user_id": "female_performer_001",
        "stage_name": "Sophia Rose",
        "bio": "Professional model and yoga instructor. Bringing beauty, grace, and positive energy to your day. Let's find inner peace and outer joy together.",
        "age": 24,
        "gender": Gender.FEMALE,
        "sexual_preference": SexualPreference.STRAIGHT,
        "ethnicity": Ethnicity.WHITE,
        "country": "United States",
        "state": "California",
        "city": "San Francisco",
        "show_exact_location": True,
        "height_cm": 168,
        "weight_kg": 55,
        "body_type": "Slim",
        "hair_color": "Blonde",
        "eye_color": "Blue",
        "experience_level": "expert",
        "specialties": ["modeling", "yoga", "wellness"],
        "languages": ["english", "french"],
        "online_status": "online",
        "timezone": "America/Los_Angeles",
        "rates": {"private_show": 75.0, "group_show": 35.0},
        "is_verified": True,
        "total_views": 25640,
        "total_likes": 1890,
        "total_shows": 234,
        "average_rating": 4.9,
        "rating_count": 203
    },
    {
        "user_id": "female_performer_002",
        "stage_name": "Luna Mystique",
        "bio": "Artist and free spirit. Love painting, music, and connecting souls. Every moment is a canvas waiting to be painted with passion and creativity.",
        "age": 22,
        "gender": Gender.FEMALE,
        "sexual_preference": SexualPreference.BISEXUAL,
        "ethnicity": Ethnicity.MIXED,
        "country": "United States",
        "state": "Oregon",
        "city": "Portland",
        "show_exact_location": False,
        "height_cm": 165,
        "weight_kg": 52,
        "body_type": "Petite",
        "hair_color": "Purple",
        "eye_color": "Green",
        "experience_level": "experienced",
        "specialties": ["art", "music", "creativity"],
        "languages": ["english"],
        "online_status": "online",
        "timezone": "America/Los_Angeles",
        "rates": {"private_show": 55.0, "group_show": 25.0},
        "is_verified": True,
        "total_views": 19430,
        "total_likes": 1245,
        "total_shows": 178,
        "average_rating": 4.8,
        "rating_count": 145
    },
    {
        "user_id": "female_performer_003",
        "stage_name": "Isabella Fuego",
        "bio": "Passionate dancer from Argentina. Tango is my language of love. Let me show you the fire that burns within and the grace that flows through movement.",
        "age": 28,
        "gender": Gender.FEMALE,
        "sexual_preference": SexualPreference.STRAIGHT,
        "ethnicity": Ethnicity.HISPANIC,
        "country": "United States",
        "state": "Texas",
        "city": "Austin",
        "show_exact_location": True,
        "height_cm": 170,
        "weight_kg": 58,
        "body_type": "Curvy",
        "hair_color": "Black",
        "eye_color": "Brown",
        "experience_level": "expert",
        "specialties": ["dancing", "tango", "latin_culture"],
        "languages": ["english", "spanish"],
        "online_status": "offline",
        "timezone": "America/Chicago",
        "rates": {"private_show": 65.0, "group_show": 30.0},
        "is_verified": True,
        "total_views": 22180,
        "total_likes": 1567,
        "total_shows": 198,
        "average_rating": 4.9,
        "rating_count": 176
    },
    {
        "user_id": "female_performer_004",
        "stage_name": "Amara Goddess",
        "bio": "Spiritual healer and meditation guide. Finding beauty in mindfulness and connection. Let me guide you on a journey of self-discovery and bliss.",
        "age": 30,
        "gender": Gender.FEMALE,
        "sexual_preference": SexualPreference.LESBIAN,
        "ethnicity": Ethnicity.BLACK,
        "country": "United States",
        "state": "Georgia",
        "city": "Atlanta",
        "show_exact_location": False,
        "height_cm": 173,
        "weight_kg": 62,
        "body_type": "Athletic",
        "hair_color": "Black",
        "eye_color": "Brown",
        "experience_level": "expert",
        "specialties": ["meditation", "healing", "spirituality"],
        "languages": ["english"],
        "online_status": "online",
        "timezone": "America/New_York",
        "rates": {"private_show": 70.0, "group_show": 32.0},
        "is_verified": True,
        "total_views": 17890,
        "total_likes": 1034,
        "total_shows": 156,
        "average_rating": 4.7,
        "rating_count": 123
    },
    {
        "user_id": "female_performer_005",
        "stage_name": "Cherry Blossom",
        "bio": "Traditional meets modern. Tea ceremony expert and cultural bridge. Bringing Eastern elegance and Western charm together in perfect harmony.",
        "age": 26,
        "gender": Gender.FEMALE,
        "sexual_preference": SexualPreference.STRAIGHT,
        "ethnicity": Ethnicity.ASIAN,
        "country": "United States",
        "state": "California",
        "city": "San Diego",
        "show_exact_location": True,
        "height_cm": 160,
        "weight_kg": 50,
        "body_type": "Petite",
        "hair_color": "Black",
        "eye_color": "Brown",
        "experience_level": "experienced",
        "specialties": ["tea_ceremony", "culture", "tradition"],
        "languages": ["english", "japanese", "korean"],
        "online_status": "online",
        "timezone": "America/Los_Angeles",
        "rates": {"private_show": 50.0, "group_show": 22.0},
        "is_verified": True,
        "total_views": 14560,
        "total_likes": 876,
        "total_shows": 132,
        "average_rating": 4.6,
        "rating_count": 108
    },
    {
        "user_id": "female_performer_006",
        "stage_name": "Raven Wild",
        "bio": "Rock musician and free spirit. Bringing raw energy and authentic connection. Life's too short for boring conversations - let's make some noise!",
        "age": 25,
        "gender": Gender.FEMALE,
        "sexual_preference": SexualPreference.PANSEXUAL,
        "ethnicity": Ethnicity.WHITE,
        "country": "United States",
        "state": "Washington",
        "city": "Seattle",
        "show_exact_location": False,
        "height_cm": 167,
        "weight_kg": 56,
        "body_type": "Slim",
        "hair_color": "Black",
        "eye_color": "Hazel",
        "experience_level": "experienced",
        "specialties": ["music", "rock", "alternative"],
        "languages": ["english"],
        "online_status": "offline",
        "timezone": "America/Los_Angeles",
        "rates": {"private_show": 45.0, "group_show": 20.0},
        "is_verified": False,
        "total_views": 11290,
        "total_likes": 678,
        "total_shows": 94,
        "average_rating": 4.5,
        "rating_count": 78
    },

    # Transgender Performers
    {
        "user_id": "trans_performer_001",
        "stage_name": "Phoenix Rising",
        "bio": "Transformation is my superpower. Life coach and motivational speaker. Let me inspire you to become your best self while we share amazing moments together.",
        "age": 27,
        "gender": Gender.TRANS_FEMALE,
        "sexual_preference": SexualPreference.PANSEXUAL,
        "ethnicity": Ethnicity.MIXED,
        "country": "United States",
        "state": "California",
        "city": "Los Angeles",
        "show_exact_location": True,
        "height_cm": 175,
        "weight_kg": 65,
        "body_type": "Slim",
        "hair_color": "Red",
        "eye_color": "Green",
        "experience_level": "expert",
        "specialties": ["coaching", "motivation", "transformation"],
        "languages": ["english", "spanish"],
        "online_status": "online",
        "timezone": "America/Los_Angeles",
        "rates": {"private_show": 65.0, "group_show": 30.0},
        "is_verified": True,
        "total_views": 20340,
        "total_likes": 1423,
        "total_shows": 187,
        "average_rating": 4.8,
        "rating_count": 156
    },
    {
        "user_id": "trans_performer_002",
        "stage_name": "Alex Vogue",
        "bio": "Fashion designer and runway model. Bringing haute couture and fierce energy to every interaction. Let's strut through life with confidence and style!",
        "age": 24,
        "gender": Gender.TRANS_MALE,
        "sexual_preference": SexualPreference.GAY,
        "ethnicity": Ethnicity.WHITE,
        "country": "United States",
        "state": "New York",
        "city": "New York City",
        "show_exact_location": True,
        "height_cm": 180,
        "weight_kg": 68,
        "body_type": "Lean",
        "hair_color": "Blonde",
        "eye_color": "Blue",
        "experience_level": "experienced",
        "specialties": ["fashion", "modeling", "design"],
        "languages": ["english", "french"],
        "online_status": "online",
        "timezone": "America/New_York",
        "rates": {"private_show": 55.0, "group_show": 25.0},
        "is_verified": True,
        "total_views": 16780,
        "total_likes": 989,
        "total_shows": 143,
        "average_rating": 4.7,
        "rating_count": 118
    },
    {
        "user_id": "trans_performer_003",
        "stage_name": "Valentina Star",
        "bio": "Professional entertainer and drag artist. Bringing glamour, humor, and unforgettable performances. Every day is a chance to shine brighter!",
        "age": 29,
        "gender": Gender.TRANS_FEMALE,
        "sexual_preference": SexualPreference.BISEXUAL,
        "ethnicity": Ethnicity.HISPANIC,
        "country": "United States",
        "state": "Florida",
        "city": "Miami",
        "show_exact_location": True,
        "height_cm": 178,
        "weight_kg": 70,
        "body_type": "Curvy",
        "hair_color": "Brown",
        "eye_color": "Brown",
        "experience_level": "expert",
        "specialties": ["drag", "entertainment", "performance"],
        "languages": ["english", "spanish"],
        "online_status": "offline",
        "timezone": "America/New_York",
        "rates": {"private_show": 70.0, "group_show": 32.0},
        "is_verified": True,
        "total_views": 23450,
        "total_likes": 1678,
        "total_shows": 211,
        "average_rating": 4.9,
        "rating_count": 189
    },
    {
        "user_id": "trans_performer_004",
        "stage_name": "River Flow",
        "bio": "Nature photographer and outdoor enthusiast. Living authentically and capturing life's beautiful moments. Let's explore the wilderness of connection together.",
        "age": 31,
        "gender": Gender.TRANS_MALE,
        "sexual_preference": SexualPreference.STRAIGHT,
        "ethnicity": Ethnicity.NATIVE_AMERICAN,
        "country": "United States",
        "state": "Arizona",
        "city": "Phoenix",
        "show_exact_location": False,
        "height_cm": 173,
        "weight_kg": 75,
        "body_type": "Athletic",
        "hair_color": "Black",
        "eye_color": "Brown",
        "experience_level": "experienced",
        "specialties": ["photography", "nature", "outdoor"],
        "languages": ["english", "navajo"],
        "online_status": "online",
        "timezone": "America/Phoenix",
        "rates": {"private_show": 50.0, "group_show": 23.0},
        "is_verified": True,
        "total_views": 12890,
        "total_likes": 734,
        "total_shows": 98,
        "average_rating": 4.6,
        "rating_count": 85
    },
    {
        "user_id": "trans_performer_005",
        "stage_name": "Quinn Harmony",
        "bio": "Music producer and sound healer. Creating beautiful frequencies and meaningful connections. Let's compose a symphony of shared moments and emotions.",
        "age": 26,
        "gender": Gender.NON_BINARY,
        "sexual_preference": SexualPreference.PANSEXUAL,
        "ethnicity": Ethnicity.WHITE,
        "country": "United States",
        "state": "Tennessee",
        "city": "Nashville",
        "show_exact_location": True,
        "height_cm": 170,
        "weight_kg": 60,
        "body_type": "Slim",
        "hair_color": "Silver",
        "eye_color": "Gray",
        "experience_level": "experienced",
        "specialties": ["music", "sound_healing", "production"],
        "languages": ["english"],
        "online_status": "online",
        "timezone": "America/Chicago",
        "rates": {"private_show": 45.0, "group_show": 20.0},
        "is_verified": False,
        "total_views": 10560,
        "total_likes": 623,
        "total_shows": 87,
        "average_rating": 4.5,
        "rating_count": 73
    },
    {
        "user_id": "trans_performer_006",
        "stage_name": "Sage Wisdom",
        "bio": "Psychology PhD and relationship counselor. Helping people connect authentically. Every conversation is an opportunity for growth and understanding.",
        "age": 33,
        "gender": Gender.TRANS_FEMALE,
        "sexual_preference": SexualPreference.LESBIAN,
        "ethnicity": Ethnicity.ASIAN,
        "country": "United States",
        "state": "California",
        "city": "Berkeley",
        "show_exact_location": False,
        "height_cm": 165,
        "weight_kg": 58,
        "body_type": "Average",
        "hair_color": "Black",
        "eye_color": "Brown",
        "experience_level": "expert",
        "specialties": ["counseling", "psychology", "relationships"],
        "languages": ["english", "korean"],
        "online_status": "offline",
        "timezone": "America/Los_Angeles",
        "rates": {"private_show": 80.0, "group_show": 35.0},
        "is_verified": True,
        "total_views": 15670,
        "total_likes": 892,
        "total_shows": 124,
        "average_rating": 4.8,
        "rating_count": 102
    }
]

async def create_sample_performers(db):
    """Create sample performer profiles in the database"""
    created_count = 0
    
    for performer_data in SAMPLE_PERFORMERS:
        # Check if performer already exists
        existing = await db.performer_profiles.find_one({"user_id": performer_data["user_id"]})
        
        if not existing:
            # Add timestamps and additional fields
            performer_data.update({
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow(),
                "last_active": datetime.utcnow() - timedelta(hours=random.randint(1, 48)),
                "show_in_search": True,
                "allow_location_search": True,
                "account_status": "active",
                "verification_level": "verified" if performer_data["is_verified"] else "basic",
                "accepts_tips": True,
                "minimum_tip": 5.0,
                "location_radius_km": 50
            })
            
            try:
                await db.performer_profiles.insert_one(performer_data)
                created_count += 1
                print(f"Created performer: {performer_data['stage_name']}")
            except Exception as e:
                print(f"Error creating performer {performer_data['stage_name']}: {str(e)}")
    
    return created_count

# Function to get a random performer for "Performer of the Month"
def get_featured_performer_candidates():
    """Get high-rated performers suitable for featuring"""
    return [p for p in SAMPLE_PERFORMERS if p["average_rating"] >= 4.7 and p["is_verified"]]